### ISSUE TITLE
PHP Warning: stat(): stat failed in ClosureStream

### ISSUE THREAD

**Issue by lvandyk** [spatie/async#38] opened 2018-05-16 13:53 UTC
Hi Spatie, firstly thank you for the amazing work!

The following code provides the above exception:

```
$pool = Pool::create();

for ($i = 0; $i < 100; $i++) {

    $pool[] = async(function () {
        return 1;
    });
}

$pool->wait();
```

Making the loop less than 50 fixes the issue. What could be the cause?

**Comment by brendt** [comment] 2018-05-16 14:17
Hi @lvandyk 

Unfortunately, I'm unable to reproduce this on my setup. My first thought would be that it has something to do with the PHP configuration on your environment?

**Comment by lvandyk** [comment] 2018-05-16 14:42
Hi @brendt thanks for the quick reply.

I'm using Laradock. I'm going to try it outside with my own Dockerfile and get back to you.

**Comment by lvandyk** [comment] 2018-05-16 15:16
Ok so it looks like something in Laradock config was causing the issue, but now I have a different exception:

` Spatie\Async\Output\ParallelError (No message).`

I see it is caused if I pass a very large array to my `Task` or with `use` when using `async` helper. The array has over 1000 strings. Something is going on with the serialization I think. 

If I pass empty array or much smaller one, it works. Feels very similar to previous issue.

**Comment by brendt** [comment] 2018-05-17 06:31
Hi @lvandyk 

Are you able to make a public repository with your failing code? It would help me to quickly debug the issue!

**Comment by lvandyk** [comment] 2018-05-19 17:44
I created a simple `Task` and returned a very large string (lots of lorem ipsum) and the callback is never fired. As soon as I reduce the size of the string by a specific amount then it works. It has to be some php.ini setting I am overlooking.

**Comment by brendt** [comment] 2018-05-22 06:44
While I'm unable to pin down the specific problem, there's an important thing to keep in mind when using this package. Communication between the parent and child processes is done via `STDIN` and `STDOUT`. There might be limitations on how much data these streams can handle based on your system. 

I always recommend to make the messages between processes as small and stateless as possible. For example: instead of passing the contents of a file, pass the path of that file and let the child process read it. 

It's important to note that not every problem can be solved with this parallel workflow. There is an overhead to creating child processes and passing data between them. It's my recommendation to only use this package for longer during tasks that can easily be split. I'm talking taks that take at least a few seconds each to execute. Otherwise you won't have any real benefit from this package.

I'm going to close this issue for now, but feel free to let me know if and how you've managed to work around your problems.

**Closed by brendt** 2018-05-22 06:44 UTC

**Comment by lvandyk** [comment] 2018-05-22 09:15
Thanks for the feedback @brendt. I am going to follow your recommendation and reduce the size of the messages.
